-- Azure SQL schema template for BriefWire
CREATE TABLE Users (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(150) NOT NULL,
  email NVARCHAR(255) NOT NULL UNIQUE,
  passwordHash NVARCHAR(255) NOT NULL,
  role NVARCHAR(20) NOT NULL DEFAULT 'reader',
  avatarUrl NVARCHAR(512),
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Articles (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  userId UNIQUEIDENTIFIER NOT NULL,
  url NVARCHAR(MAX) NOT NULL,
  title NVARCHAR(512) NOT NULL,
  publisher NVARCHAR(255),
  excerpt NVARCHAR(MAX),
  content NVARCHAR(MAX) NOT NULL,
  bias NVARCHAR(100),
  sentiment NVARCHAR(100),
  credibilityScore FLOAT,
  rawBlobPath NVARCHAR(512),
  analysisBlobPath NVARCHAR(512),
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Articles_Users FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Analyses (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  userId UNIQUEIDENTIFIER NOT NULL,
  articleId UNIQUEIDENTIFIER NOT NULL,
  type NVARCHAR(100) NOT NULL,
  result NVARCHAR(MAX) NOT NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Analyses_Users FOREIGN KEY (userId) REFERENCES Users(id),
  CONSTRAINT FK_Analyses_Articles FOREIGN KEY (articleId) REFERENCES Articles(id)
);

CREATE TABLE Bookmarks (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  userId UNIQUEIDENTIFIER NOT NULL,
  articleId UNIQUEIDENTIFIER NOT NULL,
  note NVARCHAR(MAX),
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Bookmarks_Users FOREIGN KEY (userId) REFERENCES Users(id),
  CONSTRAINT FK_Bookmarks_Articles FOREIGN KEY (articleId) REFERENCES Articles(id)
);

CREATE TABLE Claims (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  articleId UNIQUEIDENTIFIER NOT NULL,
  text NVARCHAR(MAX) NOT NULL,
  evidence NVARCHAR(MAX),
  confidence FLOAT,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Claims_Articles FOREIGN KEY (articleId) REFERENCES Articles(id)
);
